# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\git\Python\AndroidMaster\main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 601)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        #Dialog.setSizeGripEnabled(True)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_AutoZan = QtWidgets.QCheckBox(Dialog)
        self.checkBox_AutoZan.setObjectName("checkBox_AutoZan")
        self.gridLayout.addWidget(self.checkBox_AutoZan, 2, 0, 1, 1)
        self.pushButton_RunWeChat = QtWidgets.QPushButton(Dialog)
        self.pushButton_RunWeChat.setObjectName("pushButton_RunWeChat")
        self.gridLayout.addWidget(self.pushButton_RunWeChat, 0, 0, 1, 1)
        self.comboBox_StopNumber = QtWidgets.QComboBox(Dialog)
        self.comboBox_StopNumber.setObjectName("comboBox_StopNumber")
        self.comboBox_StopNumber.addItem("")
        self.comboBox_StopNumber.addItem("")
        self.comboBox_StopNumber.addItem("")
        self.gridLayout.addWidget(self.comboBox_StopNumber, 4, 1, 1, 1)
        self.textEdit_CommentText = QtWidgets.QTextEdit(Dialog)
        self.textEdit_CommentText.setObjectName("textEdit_CommentText")
        self.gridLayout.addWidget(self.textEdit_CommentText, 7, 0, 1, 2)
        self.checkBox_AutoUnlockScreen = QtWidgets.QCheckBox(Dialog)
        self.checkBox_AutoUnlockScreen.setObjectName("checkBox_AutoUnlockScreen")
        self.gridLayout.addWidget(self.checkBox_AutoUnlockScreen, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.comboBox_Resolution = QtWidgets.QComboBox(Dialog)
        self.comboBox_Resolution.setObjectName("comboBox_Resolution")
        self.comboBox_Resolution.addItem("")
        self.comboBox_Resolution.addItem("")
        self.gridLayout.addWidget(self.comboBox_Resolution, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 1, 1, 1)
        self.checkBox_AutoStopZan = QtWidgets.QCheckBox(Dialog)
        self.checkBox_AutoStopZan.setObjectName("checkBox_AutoStopZan")
        self.gridLayout.addWidget(self.checkBox_AutoStopZan, 4, 0, 1, 1)
        self.checkBox_AutoComment = QtWidgets.QCheckBox(Dialog)
        self.checkBox_AutoComment.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_AutoComment.setObjectName("checkBox_AutoComment")
        self.gridLayout.addWidget(self.checkBox_AutoComment, 6, 0, 1, 1)
        self.pushButton_AutoStartWeChat = QtWidgets.QPushButton(Dialog)
        self.pushButton_AutoStartWeChat.setObjectName("pushButton_AutoStartWeChat")
        self.gridLayout.addWidget(self.pushButton_AutoStartWeChat, 0, 1, 1, 1)
        self.comboBox_UnlockScreen = QtWidgets.QComboBox(Dialog)
        self.comboBox_UnlockScreen.setObjectName("comboBox_UnlockScreen")
        self.comboBox_UnlockScreen.addItem("")
        self.comboBox_UnlockScreen.addItem("")
        self.gridLayout.addWidget(self.comboBox_UnlockScreen, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 1)
        self.pushButton_AutoAddFriends = QtWidgets.QPushButton(Dialog)
        self.pushButton_AutoAddFriends.setObjectName("pushButton_AutoAddFriends")
        self.gridLayout.addWidget(self.pushButton_AutoAddFriends, 8, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit_Print = QtWidgets.QTextEdit(Dialog)
        self.textEdit_Print.setObjectName("textEdit_Print")
        self.verticalLayout.addWidget(self.textEdit_Print)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_ClearLog = QtWidgets.QPushButton(Dialog)
        self.pushButton_ClearLog.setObjectName("pushButton_ClearLog")
        self.horizontalLayout_2.addWidget(self.pushButton_ClearLog)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AndroidMaster"))
        self.checkBox_AutoZan.setText(_translate("Dialog", "自动点赞"))
        self.pushButton_RunWeChat.setText(_translate("Dialog", "启动微信"))
        self.comboBox_StopNumber.setItemText(0, _translate("Dialog", "前100个"))
        self.comboBox_StopNumber.setItemText(1, _translate("Dialog", "前200个"))
        self.comboBox_StopNumber.setItemText(2, _translate("Dialog", "全部"))
        self.checkBox_AutoUnlockScreen.setText(_translate("Dialog", "自动解锁屏"))
        self.label.setText(_translate("Dialog", "屏幕分辨率"))
        self.comboBox_Resolution.setItemText(0, _translate("Dialog", "1920x1080p"))
        self.comboBox_Resolution.setItemText(1, _translate("Dialog", "1280x720p"))
        self.label_2.setText(_translate("Dialog", "评论内容："))
        self.checkBox_AutoStopZan.setText(_translate("Dialog", "自动停止"))
        self.checkBox_AutoComment.setText(_translate("Dialog", "自动评论"))
        self.pushButton_AutoStartWeChat.setText(_translate("Dialog", "开始"))
        self.comboBox_UnlockScreen.setItemText(0, _translate("Dialog", "上滑解锁"))
        self.comboBox_UnlockScreen.setItemText(1, _translate("Dialog", "右滑解锁"))
        self.pushButton_AutoAddFriends.setText(_translate("Dialog", "自动确认好友"))
        self.pushButton_ClearLog.setText(_translate("Dialog", "清空"))

import src_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

